apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/xieweicarl2018/spring-boot-watch-pipeline-activity:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/xieweicarl2018/spring-boot-watch-pipeline-activity:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-boot-watch-pipeline-activity
        chartPath: charts/spring-boot-watch-pipeline-activity
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/xieweicarl2018/spring-boot-watch-pipeline-activity"
          image.tag: "{{.DIGEST_HEX}}"
